language: python
dist: xenial   # required for Python >= 3.7
python:
- '3.6'
- '3.7'
- '3.8'
env:
  global:
  - NODE_VERSION='10'
  - DOCKER_USERNAME='observatorycontrolsystem'
  - secure: AX3DL8REMuR1/RFJZiKf6UfvG6zheblZHYQ8BxDpQPH1NvbKvyLgKzFZN5v38JUvU49Yjj4v/NNRiqojF/f+bSoEqV0cKXVH1JxEFjfUHB1RadYFA6roZWmkPjCMj6Tkij2n5zDxSybyhHf3xTQ2MpwIRqYs/+nChHhYEO7g7e96lKMntj8U7E1eDoMfN32qJAYx8Q88YZNoDlZytsdW8Y1308P2wMBPcGjEFSpcO6DhkxkHupI5vTULyd99H4420fZfo7WF5GizmGAp1vrjd9/fDUcrqdrxjj+U8i2pdXhaNVeWEj5oEa4ZvNWsCxTDf7oDEoyPjVmQhbmeI0fsJeHhDX/cEJRwb72lI9AzWEruh10eh4v+EU191Ik6DFq/eV/44CrZwIeTSY4BKZ9M3/K0prOQmn+pkbdu1A+aaGEwZkR8ij4AdL8vF/R2Pcn9ySieuzkEEGS+h6/GpbZRH1GOVZwx7K5A9EoIxmrJnfyX88TyZq0I7cAt30wV/CToxyHflv2RoJJm00+WhRSwEPOc5RCZTFtI6HPoT9Kp0CX5q3MgrYnUYWl4HAKa4IbGXXA/jXOVdwAXMjlZLYvsDGjvuGdqI1wiuXy4GZHdzhth5xo0QL45kSP3p89sy7sdqsxgK+95UFIG/VXziwqsoDmpMm/mcNYp4jslr71ZQs4=
before_install:
- nvm install $NODE_VERSION
addons:
  postgresql: '9.6'
  apt:
    packages:
    - gfortran
services:
- postgresql
- docker
before_script:
- psql -c 'create database observation_portal;' -U postgres
install:
- pip install -U coverage coveralls
- pip install -r requirements.txt
- npm install
- npm run build
script: coverage run manage.py test --settings=test_settings
after_success: coveralls
deploy:
  provider: script
  script: bash docker_push
  skip_cleanup: true
  on:
    branch: test_conventions
